# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'AutoHeightTable' do
	pod 'SDWebImage', '~>3.7'
	pod 'JSONModel'
end

target 'AutoHeightTableTests' do

end

target 'AutoHeightTableUITests' do

end

